# Generated by Django 6.1 on 2026-08-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_retinalimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(default='Diabetic Retinopathy Assessment Report', max_length=255)),
                ('clinical_summary', models.TextField(blank=True)),
                ('ai_prediction', models.CharField(blank=True, max_length=100)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_medical_reports', to=settings.AUTH_USER_MODEL)),
                ('retinal_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_report', to='patients.retinalimage')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
