# Generated by Django 6.1 on 2026-08-22 11:20

import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_retinalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retinalimage',
            name='image',
            field=models.ImageField(upload_to='retinal_images/', validators=[patients.validators.validate_retinal_image]),
        ),
    ]
